name: Deploy Prod

on:
  push:
    branches:
      - prod

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt  
          pip install scikit-learn skl2onnx onnx

      - name: Download test data and ONNX model
        run: |
          mkdir -p data models
          curl -L -o data/test_data.json "https://github.com/user-attachments/files/28938272/test_data.json"
          curl -L -o models/credit_model.onnx "https://github.com/JulianEspinosaUrresti/crespo-cuervo-espinosa-mlops-ProyectoFinal/releases/download/v1.0-model/credit_model.onnx"    

      - name: Run tests
        run: |
          pytest tests -s

  build:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t proyecto-final-prod -f docker/Dockerfile .