name: Deploy Prod

on:
  push:
    branches:
      - prod

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install scikit-learn skl2onnx onnx

      - name: Generar modelo ONNX
        run: |
          python app/create_model.py

  build:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t proyecto-final-prod -f docker/Dockerfile .